package a2;

import a2.erd.ERD;
import a2.sql.Database;


public class ImplementMe {
    /**
     * This function converts an ERD object into a Database object
     * The Database object should correspond to a fully correct implementation
     * of the ERD, including both data structure and constraints, such that the
     * CREATE TABLE statements generated by the Database object will populate an
     * empty MySQL database to exactly implement the conceptual design communicated
     * by the ERD.
     * NOTE:    DO NOT CHANGE THE SIGNATURE OF THIS CLASS AND THE FUNCTION
     *          HOWEVER, YOU CAN ADD CUSTOM METHODS AND VARIABLES TO THIS CLASS
     */
    public Database convertToDatabase(ERD erd) {
        //TODO: Implement me!
        return null;
    }
}
