-- Show all counties ordered by their total
-- number of employees across all industries
-- Tie-break with the county id in ascending order.
-- 1.1 marks: <5 operators
-- 1.0 marks: <6 operators
-- 0.8 marks: correct answer
