-- Retrieve alphabetically the abbreviations of the states
-- in which one can find the ten counties that had the
-- largest (absolute) increase in employed persons
-- between 2008 and 2016.
-- 1.02 marks: <11 operators
-- 1.00 marks: <12 operators
-- 0.90 marks: <14 operators
-- 0.80 marks: correct answer
